.\" (C) Copyright 2022 kj <kj@aetherlabs.io>,
.\"
.TH Aether WRAPPER "August 20 2022"
.SH NAME
aether\-wrapper a simple baSH and PYthon wrapper around node executables in context

.SH SYNOPSIS
.B #!/usr/bin/aether\-wrapper
.br
.SH DESCRIPTION
This manual page documents briefly the different
.B aether\-wrapper
executions. The wrapper will quit if any NON-ZERO exit codes arise from invoking any 
bash or python3 scripts using the shebang. will also limit the context of access in the
system files
.PP
\fBaether\-wrapper\fP is a wapper to any program and/or script created by aether
.SH COMMANDS
This program is used as a wrapper MAINLY in the pre-prended file as a shebang and should not be used in direct terminal invokation such as most GNU commands.

.SH SEE ALSO
.BR aether (1).
.BR aether-reader (1),
.BR aether-jsonifier (1).
.BR aether-configurator (1).
.br
