/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ContextOwner, ContextOwnerInterface } from "../ContextOwner";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ContextOwner__factory {
  static readonly abi = _abi;
  static createInterface(): ContextOwnerInterface {
    return new utils.Interface(_abi) as ContextOwnerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContextOwner {
    return new Contract(address, _abi, signerOrProvider) as ContextOwner;
  }
}
