/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AetherFactoryInterface extends ethers.utils.Interface {
  functions: {
    "aetherBonds()": FunctionFragment;
    "aetherDAO()": FunctionFragment;
    "aetherFactory()": FunctionFragment;
    "aetherHUB()": FunctionFragment;
    "aetherID()": FunctionFragment;
    "aetherKeeper()": FunctionFragment;
    "aetherRouter()": FunctionFragment;
    "aetherSetup()": FunctionFragment;
    "aetherToken()": FunctionFragment;
    "contractsDeployed()": FunctionFragment;
    "deployContract(bytes,uint256)": FunctionFragment;
    "deployNode()": FunctionFragment;
    "deployProxy(address,uint256)": FunctionFragment;
    "factoryIsNode(address)": FunctionFragment;
    "factoryIsProxy(address)": FunctionFragment;
    "getAetherAddress(uint256)": FunctionFragment;
    "getDeploymentAddress(uint256)": FunctionFragment;
    "nodesDeployed()": FunctionFragment;
    "setupAether()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aetherBonds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aetherDAO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aetherFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aetherHUB", values?: undefined): string;
  encodeFunctionData(functionFragment: "aetherID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aetherKeeper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aetherRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aetherSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aetherToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractsDeployed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployContract",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployNode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployProxy",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "factoryIsNode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "factoryIsProxy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAetherAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeploymentAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nodesDeployed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setupAether",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "aetherBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aetherDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aetherFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aetherHUB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "aetherID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aetherKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aetherRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aetherSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aetherToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractsDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "factoryIsNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "factoryIsProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAetherAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeploymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nodesDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupAether",
    data: BytesLike
  ): Result;

  events: {
    "ContractDeployed(address,address,uint256)": EventFragment;
    "NodeDeployed(address,address,uint256,uint256)": EventFragment;
    "ProxyDeployed(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NodeDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProxyDeployed"): EventFragment;
}

export type ContractDeployedEvent = TypedEvent<
  [string, string, BigNumber] & {
    Contract: string;
    Proxy: string;
    DeploymentID: BigNumber;
  }
>;

export type NodeDeployedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber] & {
    Node: string;
    Owner: string;
    Timestamp: BigNumber;
    DeploymentID: BigNumber;
  }
>;

export type ProxyDeployedEvent = TypedEvent<
  [string, string, BigNumber] & {
    Proxy: string;
    ProxyTo: string;
    DeploymentID: BigNumber;
  }
>;

export class AetherFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AetherFactoryInterface;

  functions: {
    aetherBonds(overrides?: CallOverrides): Promise<[string]>;

    aetherDAO(overrides?: CallOverrides): Promise<[string]>;

    aetherFactory(overrides?: CallOverrides): Promise<[string]>;

    aetherHUB(overrides?: CallOverrides): Promise<[string]>;

    aetherID(overrides?: CallOverrides): Promise<[BigNumber]>;

    aetherKeeper(overrides?: CallOverrides): Promise<[string]>;

    aetherRouter(overrides?: CallOverrides): Promise<[string]>;

    aetherSetup(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    aetherToken(overrides?: CallOverrides): Promise<[string]>;

    contractsDeployed(overrides?: CallOverrides): Promise<[BigNumber]>;

    deployContract(
      cCode: BytesLike,
      ticketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployNode(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployProxy(
      proxyTo: string,
      ticketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factoryIsNode(addr: string, overrides?: CallOverrides): Promise<[boolean]>;

    factoryIsProxy(addr: string, overrides?: CallOverrides): Promise<[boolean]>;

    getAetherAddress(
      contractId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { contractAddress: string }>;

    getDeploymentAddress(
      _cIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    nodesDeployed(overrides?: CallOverrides): Promise<[BigNumber]>;

    setupAether(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  aetherBonds(overrides?: CallOverrides): Promise<string>;

  aetherDAO(overrides?: CallOverrides): Promise<string>;

  aetherFactory(overrides?: CallOverrides): Promise<string>;

  aetherHUB(overrides?: CallOverrides): Promise<string>;

  aetherID(overrides?: CallOverrides): Promise<BigNumber>;

  aetherKeeper(overrides?: CallOverrides): Promise<string>;

  aetherRouter(overrides?: CallOverrides): Promise<string>;

  aetherSetup(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  aetherToken(overrides?: CallOverrides): Promise<string>;

  contractsDeployed(overrides?: CallOverrides): Promise<BigNumber>;

  deployContract(
    cCode: BytesLike,
    ticketId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployNode(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployProxy(
    proxyTo: string,
    ticketId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factoryIsNode(addr: string, overrides?: CallOverrides): Promise<boolean>;

  factoryIsProxy(addr: string, overrides?: CallOverrides): Promise<boolean>;

  getAetherAddress(
    contractId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getDeploymentAddress(
    _cIdx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  nodesDeployed(overrides?: CallOverrides): Promise<BigNumber>;

  setupAether(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    aetherBonds(overrides?: CallOverrides): Promise<string>;

    aetherDAO(overrides?: CallOverrides): Promise<string>;

    aetherFactory(overrides?: CallOverrides): Promise<string>;

    aetherHUB(overrides?: CallOverrides): Promise<string>;

    aetherID(overrides?: CallOverrides): Promise<BigNumber>;

    aetherKeeper(overrides?: CallOverrides): Promise<string>;

    aetherRouter(overrides?: CallOverrides): Promise<string>;

    aetherSetup(overrides?: CallOverrides): Promise<void>;

    aetherToken(overrides?: CallOverrides): Promise<string>;

    contractsDeployed(overrides?: CallOverrides): Promise<BigNumber>;

    deployContract(
      cCode: BytesLike,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    deployNode(overrides?: CallOverrides): Promise<string>;

    deployProxy(
      proxyTo: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    factoryIsNode(addr: string, overrides?: CallOverrides): Promise<boolean>;

    factoryIsProxy(addr: string, overrides?: CallOverrides): Promise<boolean>;

    getAetherAddress(
      contractId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getDeploymentAddress(
      _cIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    nodesDeployed(overrides?: CallOverrides): Promise<BigNumber>;

    setupAether(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "ContractDeployed(address,address,uint256)"(
      Contract?: string | null,
      Proxy?: string | null,
      DeploymentID?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { Contract: string; Proxy: string; DeploymentID: BigNumber }
    >;

    ContractDeployed(
      Contract?: string | null,
      Proxy?: string | null,
      DeploymentID?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { Contract: string; Proxy: string; DeploymentID: BigNumber }
    >;

    "NodeDeployed(address,address,uint256,uint256)"(
      Node?: string | null,
      Owner?: string | null,
      Timestamp?: null,
      DeploymentID?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        Node: string;
        Owner: string;
        Timestamp: BigNumber;
        DeploymentID: BigNumber;
      }
    >;

    NodeDeployed(
      Node?: string | null,
      Owner?: string | null,
      Timestamp?: null,
      DeploymentID?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        Node: string;
        Owner: string;
        Timestamp: BigNumber;
        DeploymentID: BigNumber;
      }
    >;

    "ProxyDeployed(address,address,uint256)"(
      Proxy?: string | null,
      ProxyTo?: string | null,
      DeploymentID?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { Proxy: string; ProxyTo: string; DeploymentID: BigNumber }
    >;

    ProxyDeployed(
      Proxy?: string | null,
      ProxyTo?: string | null,
      DeploymentID?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { Proxy: string; ProxyTo: string; DeploymentID: BigNumber }
    >;
  };

  estimateGas: {
    aetherBonds(overrides?: CallOverrides): Promise<BigNumber>;

    aetherDAO(overrides?: CallOverrides): Promise<BigNumber>;

    aetherFactory(overrides?: CallOverrides): Promise<BigNumber>;

    aetherHUB(overrides?: CallOverrides): Promise<BigNumber>;

    aetherID(overrides?: CallOverrides): Promise<BigNumber>;

    aetherKeeper(overrides?: CallOverrides): Promise<BigNumber>;

    aetherRouter(overrides?: CallOverrides): Promise<BigNumber>;

    aetherSetup(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    aetherToken(overrides?: CallOverrides): Promise<BigNumber>;

    contractsDeployed(overrides?: CallOverrides): Promise<BigNumber>;

    deployContract(
      cCode: BytesLike,
      ticketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployNode(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployProxy(
      proxyTo: string,
      ticketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factoryIsNode(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    factoryIsProxy(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAetherAddress(
      contractId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDeploymentAddress(
      _cIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nodesDeployed(overrides?: CallOverrides): Promise<BigNumber>;

    setupAether(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aetherBonds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherDAO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherHUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherKeeper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    aetherSetup(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    aetherToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contractsDeployed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployContract(
      cCode: BytesLike,
      ticketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployNode(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployProxy(
      proxyTo: string,
      ticketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factoryIsNode(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factoryIsProxy(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAetherAddress(
      contractId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeploymentAddress(
      _cIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nodesDeployed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setupAether(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
