/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAetherCallInterface extends ethers.utils.Interface {
  functions: {
    "submitTransaction(uint256,address,uint256[],bytes4[],bytes[])": FunctionFragment;
    "tempSubmitTxn(uint256,address,bytes4,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [BigNumberish, string, BigNumberish[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "tempSubmitTxn",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tempSubmitTxn",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAetherCall extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAetherCallInterface;

  functions: {
    submitTransaction(
      arg0: BigNumberish,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BytesLike[],
      arg4: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tempSubmitTxn(
      arg0: BigNumberish,
      arg1: string,
      arg2: BytesLike,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  submitTransaction(
    arg0: BigNumberish,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BytesLike[],
    arg4: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tempSubmitTxn(
    arg0: BigNumberish,
    arg1: string,
    arg2: BytesLike,
    arg3: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    submitTransaction(
      arg0: BigNumberish,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BytesLike[],
      arg4: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    tempSubmitTxn(
      arg0: BigNumberish,
      arg1: string,
      arg2: BytesLike,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    submitTransaction(
      arg0: BigNumberish,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BytesLike[],
      arg4: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tempSubmitTxn(
      arg0: BigNumberish,
      arg1: string,
      arg2: BytesLike,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    submitTransaction(
      arg0: BigNumberish,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BytesLike[],
      arg4: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tempSubmitTxn(
      arg0: BigNumberish,
      arg1: string,
      arg2: BytesLike,
      arg3: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
