/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITreasury, ITreasuryInterface } from "../ITreasury";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "BondId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "TreasuryOwnership",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "DefaultValue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "BondOwner",
        type: "address",
      },
    ],
    name: "BondDefaulted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "BondId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "QueuePosition",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "BondValue",
        type: "uint256",
      },
    ],
    name: "BondQueued",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "BondId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "TreasuryOwnership",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "BondOwner",
        type: "address",
      },
    ],
    name: "boneMade",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "auctionBond",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "bondEval",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "issueBond",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "maturity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "swapBond",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITreasury__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryInterface {
    return new utils.Interface(_abi) as ITreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITreasury {
    return new Contract(address, _abi, signerOrProvider) as ITreasury;
  }
}
