
ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

HUB_nativeBlockNum = 'nativeBlockNum'
HUB_aetherBlockNum = 'aetherBlockNum'
HUB_roll = 'roll'
HUB_chains = 'aetheringChains'
HUB_masterhash = 'MASTER_HASH'
HUB_aetherer = 'aetheringAddress'
HUB_aetherAddress = 'callerAAddress'
HUB_aetherTxnHash = 'getATransaction'

DAO_VAR_PROPOSAL_TIME = 'proposalTime'
DAO_VAR_SIGNERS_THRESHOLD = 'signersThreshold'
DAO_VAR_NODE_THRESHOLD = 'nodeThreshold'
DAO_VAR_NODE_STAKING_TIME = 'nodeStakingTime'
DAO_VAR_BOND_MATURITY_TIME = 'bondMaturityTime'
DAO_VAR_TRANSACTION_THRESHOLD = 'transactionThreshold'
DAO_VAR_HOLDER_THRESHOLD = 'holderThreshold'
DAO_VAR_REWARDS_TREASURY = 'rewardsTreasury'
DAO_VAR_TREASURY_THRESHOLD = 'treasuryThreshold'
DAO_VAR_DEPLETION_MULTIPLIER = 'depletionMultiplier'
DAO_VAR_DEPLETION_DIVISOR = 'depletionDivisor'
DAO_VAR_REWARD_LEDGER = 'rewardLedger'
DAO_VAR_GAS_PRICE = 'gasPrice'
DAO_VAR_TARGET_GAS = 'targetGas'
DAO_VAR_TARGET_TRANSACTIONS = 'targetTransactions'
DAO_VAR_MAX_BPB = 'MaxBPB'
DAO_VAR_MAX_TPB = 'MaxTPB'


