/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAetherReceiver,
  IAetherReceiverInterface,
} from "../IAetherReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAetherReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IAetherReceiverInterface {
    return new utils.Interface(_abi) as IAetherReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAetherReceiver {
    return new Contract(address, _abi, signerOrProvider) as IAetherReceiver;
  }
}
