/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAetherTest, IAetherTestInterface } from "../IAetherTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAetherTest__factory {
  static readonly abi = _abi;
  static createInterface(): IAetherTestInterface {
    return new utils.Interface(_abi) as IAetherTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAetherTest {
    return new Contract(address, _abi, signerOrProvider) as IAetherTest;
  }
}
