#!/bin/python3
from os.path import join,dirname
import sys
sys.path.append( join( dirname( sys.path[0] ) , 'DEFAULT.node' ) )

from aether.node import Node

if __name__ == '__main__':
	_node = Node( sys.argv[-2] , sys.argv[-1] )
